name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  # unit:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 16
  #     - run: npm ci
  #     - run: npm test

  # e2e:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 16
  #     - run: npm ci
  #     - run: npm run build
  #     - run: npx playwright install
  #     - run: npm run e2e

  release:
    # needs: [unit, e2e]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ github.ref }}

      - name: changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4.0.0-rc03
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: RELEASE ${{ github.ref }}
          body: |
            RELEASE ${{ github.ref }}
            fromTag: ${{ steps.changelog.outputs.fromTag}}
            toTag: ${{ steps.changelog.outputs.toTag}}
            changelog: ${{ steps.changelog.outputs.changelog }}
            commits: ${{ steps.changelog.outputs.commits }}
            cache: ${{ steps.changelog.outputs.cache }}
          draft: false
          prerelease: false


      - run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: issue
        id: issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh issue create --title "RELEASE ${{ github.ref }}" --body "Дата релиза $NOW \n Автор ${{ steps.changelog.outputs.owner }} \n Версия релиза ${{ github.ref }} \n changelog ${{steps.github_release.outputs.changelog}}"

